### ISSUE TITLE
test-based tab should shows diffs between before and after

### ISSUE THREAD

**Issue by gustavoasoares** [lucasmf/HerokuUI#27]
Currently, it shoulds diffs between before and synthesizedAfter, which is not the real scenario of using test-based clustering

**Comment by eglassman** [comment]
This seems pretty trivial, but I'm not soo familiar with the template code that renders the diffs. @gustavoasoares touched that most recently when he refactored the views (thank you for that, Gustavo!). One of us front-end folks should do it though, so he can focus on backend. @ryosuzuki? @lucasmf?

**Comment by eglassman** [comment]
So, now, when we read in the data, we generate diffs for both the before --> synthesized after and the before --> actual (student written) after. Now all we need to do is render the latter diffs in the second (test) tab

**Comment by eglassman** [comment]
Done.
