### ISSUE TITLE
UI bug--is this a "no rule" cluster?

### ISSUE THREAD

**Issue by eglassman** [lucasmf/HerokuUI#3]
![uiprototypebug](https://cloud.githubusercontent.com/assets/2320194/17983236/71ebbca0-6ac0-11e6-90e8-2a346970e9dc.jpg)

**Comment by lucasmf** [comment]
Me and Gustavo talked about this one, what we think is happening is the following. A homework is a composed by more than one problem, so we are splitting the homework to treat each problem separately. If the homework has something wrong, although it might have one or more correct solution, the clustering algorithm will try to create a transformation for it.

**Comment by eglassman** [comment]
Hum. :/ I still don't understand. I haven't seen this recently in the UI at least. I'm closing.
