### ISSUE TITLE
Progress bars

### ISSUE THREAD

**Issue by andrewhead** [lucasmf/HerokuUI#32]
Maybe it makes sense to have progress bars for each tab, and one progress bar overall, since I think, for separating conditions, we need to keep hints within tabs, not across tabs.

From issue comments in https://github.com/lucasmf/HerokuUI/issues/6

**Comment by ryosuzuki** [comment]
Basically I added the progress bar based on the `(finished_cluster_number)/(total_cluster_number)`, but it seems better to show the progress based on `(finished_fixes)/(total_bugs)`

**Comment by ryosuzuki** [comment]
![screen shot 2016-09-23 at 4 51 25 pm](https://cloud.githubusercontent.com/assets/1428255/18803531/074664ae-81ae-11e6-8d1e-dd18a26663f8.png)

**Comment by ryosuzuki** [comment]
Show progress bar based on the question number

**Comment by ryosuzuki** [comment]
Now, showing the correct progress bar based on the `finished_count / total_count`.

![screen shot 2016-09-23 at 7 42 16 pm](https://cloud.githubusercontent.com/assets/1428255/18805280/21bcfaba-81c6-11e6-8ff7-8e26c6bad7a4.png)
