### ISSUE TITLE
hints need to be associated with a problem number, not just a cluster_id

### ISSUE THREAD

**Issue by eglassman** [lucasmf/HerokuUI#6]

**Comment by eglassman** [comment]
This is obviously a problem that's critical.

**Comment by eglassman** [comment]
Apparently, it's being entered into the db with the problem number (good) but being rendered for all problems.

**Comment by eglassman** [comment]
Maybe it makes sense to have progress bars for each tab, and one progress bar overall, since I think, for separating conditions, we need to keep hints within tabs, not across tabs.

**Comment by ryosuzuki** [comment]
We can add separate hints for different tabs. 
Now we can work on issue #32 based on this data schema.

![w5e1eltyes](https://cloud.githubusercontent.com/assets/1428255/18801519/53ca36ec-81a0-11e6-87b8-1745466581f8.gif)
