### ISSUE TITLE
improve efficiency of adding or editing a hint

### ISSUE THREAD

**Issue by eglassman** [lucasmf/HerokuUI#7]
make hint directly editable, pressing enter should submit hint

**Comment by ryosuzuki** [comment]
First, we need to show the hint associated with `question_number` and `cluster_id`.

**Comment by ryosuzuki** [comment]
Fixed, and close the issue.
![zunimwdgxf](https://cloud.githubusercontent.com/assets/1428255/18798715/0e69a29a-8191-11e6-8a5e-6149689d7897.gif)

**Comment by ryosuzuki** [comment]
@eglassman By the way, did you change the name `hint` to `fixes` in `flaskr.py`? 
I'm using fixes as hints, though. I was a bit confused about the naming.
